# Generated by Django 3.1.7 on 2021-05-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'creator', 'publisher', 'issued')},
        ),
    ]
